// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(SiteDb))]
    [Migration("20180619111647_AddingNewEntities")]
    partial class AddingNewEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressCountryId");

                    b.Property<int?>("AddressProvinceId");

                    b.Property<int?>("AddressStreetId");

                    b.HasKey("AddressId");

                    b.HasIndex("AddressCountryId");

                    b.HasIndex("AddressProvinceId");

                    b.HasIndex("AddressStreetId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DataAccess.Entities.AddressCountry", b =>
                {
                    b.Property<int>("AddressCountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.HasKey("AddressCountryId");

                    b.ToTable("AddressCountries");
                });

            modelBuilder.Entity("DataAccess.Entities.AddressProvince", b =>
                {
                    b.Property<int>("AddressProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProvinceName");

                    b.HasKey("AddressProvinceId");

                    b.ToTable("AddressProvinces");
                });

            modelBuilder.Entity("DataAccess.Entities.AddressStreet", b =>
                {
                    b.Property<int>("AddressStreetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PostalCode");

                    b.Property<string>("StreetName");

                    b.HasKey("AddressStreetId");

                    b.ToTable("AddressStreets");
                });

            modelBuilder.Entity("DataAccess.Entities.BlogDetail", b =>
                {
                    b.Property<int>("BlogDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlogAuthor");

                    b.Property<string>("BlogBody");

                    b.Property<string>("BlogClosingCaption");

                    b.Property<string>("BlogImagePath");

                    b.Property<string>("BlogIntro");

                    b.Property<string>("BlogRemarks");

                    b.Property<DateTime>("BlogStartingDate");

                    b.Property<string>("BlogTitle");

                    b.Property<int?>("BlogTypeId");

                    b.Property<DateTime>("BlogWrittenOn");

                    b.HasKey("BlogDetailId");

                    b.HasIndex("BlogTypeId");

                    b.ToTable("BlogDetails");
                });

            modelBuilder.Entity("DataAccess.Entities.BlogType", b =>
                {
                    b.Property<int>("BlogTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlogName");

                    b.HasKey("BlogTypeId");

                    b.ToTable("BlogTypes");
                });

            modelBuilder.Entity("DataAccess.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("ClientName");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.HasKey("ClientId");

                    b.HasIndex("AddressId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DataAccess.Entities.CoreBlog", b =>
                {
                    b.Property<int>("CoreBlogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BlogDetailId");

                    b.Property<int?>("CoreMemberId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("CoreBlogId");

                    b.HasIndex("BlogDetailId");

                    b.HasIndex("CoreMemberId");

                    b.ToTable("CoreBlogs");
                });

            modelBuilder.Entity("DataAccess.Entities.CoreMember", b =>
                {
                    b.Property<int>("CoreMemberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<int?>("PersonId");

                    b.HasKey("CoreMemberId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PersonId");

                    b.ToTable("CoreMembers");
                });

            modelBuilder.Entity("DataAccess.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("PersonEmail");

                    b.Property<string>("PersonHome");

                    b.Property<string>("PersonIdentityNumber");

                    b.Property<string>("PersonMobile");

                    b.Property<string>("PersonName");

                    b.Property<string>("PersonSurname");

                    b.Property<string>("PersonWork");

                    b.HasKey("PersonId");

                    b.HasIndex("AddressId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DataAccess.Entities.Address", b =>
                {
                    b.HasOne("DataAccess.Entities.AddressCountry", "AddressCountry")
                        .WithMany()
                        .HasForeignKey("AddressCountryId");

                    b.HasOne("DataAccess.Entities.AddressProvince", "AddressProvince")
                        .WithMany()
                        .HasForeignKey("AddressProvinceId");

                    b.HasOne("DataAccess.Entities.AddressStreet", "AddressStreet")
                        .WithMany()
                        .HasForeignKey("AddressStreetId");
                });

            modelBuilder.Entity("DataAccess.Entities.BlogDetail", b =>
                {
                    b.HasOne("DataAccess.Entities.BlogType", "BlogType")
                        .WithMany()
                        .HasForeignKey("BlogTypeId");
                });

            modelBuilder.Entity("DataAccess.Entities.Client", b =>
                {
                    b.HasOne("DataAccess.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("DataAccess.Entities.CoreBlog", b =>
                {
                    b.HasOne("DataAccess.Entities.BlogDetail", "BlogDetail")
                        .WithMany()
                        .HasForeignKey("BlogDetailId");

                    b.HasOne("DataAccess.Entities.CoreMember", "CoreMember")
                        .WithMany()
                        .HasForeignKey("CoreMemberId");
                });

            modelBuilder.Entity("DataAccess.Entities.CoreMember", b =>
                {
                    b.HasOne("DataAccess.Entities.Client")
                        .WithMany("CoreMembers")
                        .HasForeignKey("ClientId");

                    b.HasOne("DataAccess.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("DataAccess.Entities.Person", b =>
                {
                    b.HasOne("DataAccess.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
